version: '2.0'
services:
  celebr8-db:
    image: mongo:latest
    container_name: "celebr8-db"
    # TODO: should parameterize these at some point...
    environment:
      - MONGO_INITDB_ROOT_USERNAME=celebr8
      - MONGO_INITDB_ROOT_PASSWORD=celebr8!
      - MONGO_INITDB_DATABASE=celebr8
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - celebr8

networks:
  celebr8: